sudo: required
services:
    - docker

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-ap-south-1-509006680370"
    bucket_path: "frontend"
    edge: true
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY